version: '3.8'

volumes:
  mongo_data:

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    environment:
      - MODE=dev
      - MONGOURI=mongodb://koya1234:pass1234@mongo:27017
      - PORT=7778
      - ADMIN_NAME=itsme
      - ADMIN_PASSWORD=trustme
      - JWT_SECRET_KEY=secret
    volumes:
      - .:/api
    ports:
      - "7778:7778"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: koya1234
      MONGO_INITDB_ROOT_PASSWORD: pass1234
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db